### ISSUE TITLE
[Setting] 프로젝트 초기세팅

### ISSUE THREAD

**Issue by dltnals317** [SOPT-all/35-COLLABORATION-SERVER-CARROT#1]
# 💬 ISSUE 
- 프로젝트 초기세팅

# ☑️ To-Do
- [x] spring boot 프로젝트 생성
- [x] 필요한 dependency 추가
- [x] dependency 코드 정리
